name: dotnet package

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: ["2.2.103"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: "2.2.103"
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Generate Package
        run: dotnet pack -o artifact/nupkg # -p:Version=2.0 (get tag env variable)
      - uses: actions/upload-artifact@v2
        with:
          name: package
          path: artifact/nupkg/
